### ISSUE TITLE
error fetching forecast due to invalid Condition

### ISSUE THREAD

**Issue by robert-alfaro** [jeeftor/weatherflow4py#21]
just updated to HA 2024.3 and installed `weatheflow_cloud` integration. It worked fine until about 15 minutes later when it began to rain outside...it went unavailable. I checked logs and a crash occurred in this layer of code. Seems the `Condition` enum is incomplete.

```
Logger: homeassistant.components.weatherflow_cloud
Source: helpers/update_coordinator.py:318
integration: WeatherflowCloud
First occurred: 3:02:03 PM (10 occurrences)
Last logged: 3:27:28 PM

Unexpected error fetching weatherflow_cloud data: 'Light Rain' is not a valid Condition
Unexpected error fetching weatherflow_cloud data: 'Heavy Rain' is not a valid Condition
Unexpected error fetching weatherflow_cloud data: 'Moderate Rain' is not a valid Condition
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 318, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/weatherflow_cloud/coordinator.py", line 35, in _async_update_data
    return await self.weather_api.get_all_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/weatherflow4py/api.py", line 137, in get_all_data
    weather=await self.async_get_forecast(station_id=station.station_id),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/weatherflow4py/api.py", line 85, in async_get_forecast
    return await self._make_request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/weatherflow4py/api.py", line 44, in _make_request
    response_model.from_json(data)
  File "/usr/local/lib/python3.12/site-packages/dataclasses_json/api.py", line 63, in from_json
    return cls.from_dict(kvs, infer_missing=infer_missing)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/dataclasses_json/api.py", line 70, in from_dict
    return _decode_dataclass(cls, kvs, infer_missing)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/dataclasses_json/core.py", line 216, in _decode_dataclass
    value = _decode_dataclass(field_type, field_value,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/dataclasses_json/core.py", line 220, in _decode_dataclass
    init_kwargs[field.name] = _decode_generic(field_type,
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/dataclasses_json/core.py", line 272, in _decode_generic
    res = type_(value)
          ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/enum.py", line 744, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/enum.py", line 1158, in __new__
    raise ve_exc
ValueError: 'Light Rain' is not a valid Condition
```

**Comment by jeeftor** [comment]
Living in Colorado I don't have the best chance to test all the conditions. I'll get it updated tomorrow or tonight. 

I expect a bunch of these errors coming down the way :)

**Comment by jeeftor** [comment]
Well duh:

```python
    CLEAR = "Clear"
    RAIN_LIKELY = "Rain Likely"
    RAIN_POSSIBLE = "Rain Possible"
    SNOW = "Snow"
    SNOW_POSSIBLE = "Snow Possible"
    WINTRY_MIX_LIKELY = "Wintry Mix Likely"
    WINTRY_MIX_POSSIBLE = "Wintry Mix Possible"
    THUNDERSTORMS_LIKELY = "Thunderstorms Likely"
    THUNDERSTORMS_POSSIBLE = "Thunderstorms Possible"
    WINDY = "Windy"
    FOGGY = "Foggy"
    CLOUDY = "Cloudy"
    PARTLY_CLOUDY = "Partly Cloudy"
    VERY_LIGHT_RAIN = "Very Light Rain"
```

Yea looks like I'm missing a few rain states :)

**Comment by jeeftor** [comment]
I've thus far seen A LOT of discrepancies between the API docs and the reality :) ... Once this new version gets up to pypi -> I'll get a PR out.

**Comment by robert-alfaro** [comment]
yea totally.. the API docs here match your implementation (or the other way around :stuck_out_tongue:) https://weatherflow.github.io/Tempest/api/swagger/#!/forecast/getBetterForecast

**Comment by robert-alfaro** [comment]
Looking around at [pyweatherflow](https://github.com/briis/pyweatherflow_forecast/blob/eeb319181fd3b73ce1cd4748870a0185adfcf163/pyweatherflow_forecast/wffcst_lib.py#L152) (hasn't had this problem), they're just passing the string through from the http response through to HA.
